runtime: java
env: flex
runtime_config:
  jdk: openjdk8
handlers:
- url: /.*
  script: this field is required, but ignored
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
manual_scaling:
  instances: 1